@version: 3.38

source s_nessus_messages {
    file("/opt/nessus/var/nessus/logs/nessusd.messages"
         follow-freq(1)
         flags(no-parse)
         program-override("nessus")
         default-facility(local5)
         default-priority(info));
};

source s_nessus_backend {
    file("/opt/nessus/var/nessus/logs/backend.log"
         follow-freq(1)
         flags(no-parse)
         program-override("nessus")
         default-facility(local5)
         default-priority(info));
};

source s_nessus_www {
    file("/opt/nessus/var/nessus/logs/www_server.log"
         follow-freq(1)
         flags(no-parse)
         program-override("nessus")
         default-facility(local5)
         default-priority(info));
};

source s_nessus_cli {
    file("/opt/nessus/var/nessus/logs/nessuscli.log"
         follow-freq(1)
         flags(no-parse)
         program-override("nessus")
         default-facility(local5)
         default-priority(info));
};

destination d_nessus_remote {
    network("<SYSLOG_FORWARDER_IP>"
            transport("udp")
            port(514));
};

log { source(s_nessus_messages); destination(d_nessus_remote); };
log { source(s_nessus_backend);  destination(d_nessus_remote); };
log { source(s_nessus_www);      destination(d_nessus_remote); };
log { source(s_nessus_cli);      destination(d_nessus_remote); };
